project_id = "cnmdwgdizfrvyplllmdn"

[functions.scrape-products]
verify_jwt = true

[functions.check-prices]
verify_jwt = true

[functions.get-analytics]
verify_jwt = true

[functions.update-exchange-rates]
verify_jwt = false

[functions.refresh-product-prices]
verify_jwt = true

[functions.ai-product-search]
verify_jwt = true

[functions.user-refresh-prices]
verify_jwt = true

[functions.delete-expired-promo-codes]
verify_jwt = false

[functions.admin-refresh-krolist-prices]
verify_jwt = true

[functions.translate-text]
verify_jwt = true

[functions.generate-sitemap]
verify_jwt = false

[functions.process-sticker-image]
verify_jwt = false

[functions.admin-login-guard]
verify_jwt = false
