project_id = "cnmdwgdizfrvyplllmdn"

[functions.scrape-products]
verify_jwt = true

[functions.check-prices]
verify_jwt = true

[functions.get-analytics]
verify_jwt = true

[functions.update-exchange-rates]
verify_jwt = false
